// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Aaron",
            "email": "duaaron519@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "登录"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "loginInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.loginInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/movie/info/{movie_id}": {
            "get": {
                "description": "获取电影信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "电影"
                ],
                "summary": "获取电影信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "电影ID",
                        "name": "movie_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/movie/list": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "电影"
                ],
                "summary": "分页获取电影信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/movie/upload": {
            "post": {
                "description": "上传电影信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "电影"
                ],
                "summary": "上传电影信息",
                "responses": {}
            }
        },
        "/oss/upload/applayUpload": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件上传"
                ],
                "summary": "申请上传文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "存储ID",
                        "name": "X-Oss-StorageId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bucket名称",
                        "name": "X-Oss-BucketId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "目录ID",
                        "name": "X-Oss-DirectoryId",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "$ref": "#/definitions/response.Result"
                        }
                    }
                }
            }
        },
        "/oss/upload/initMultipartUpload": {
            "post": {
                "description": "初始化分片上传",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件上传"
                ],
                "summary": "初始化分片上传",
                "parameters": [
                    {
                        "description": "uploadInfo",
                        "name": "uploadInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/aws.UploadInfo"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/oss/upload/multipart/abort/{fid}": {
            "post": {
                "description": "中断分片上传",
                "tags": [
                    "文件上传"
                ],
                "summary": "中断分片上传",
                "parameters": [
                    {
                        "type": "string",
                        "description": "upload_id",
                        "name": "X-Oss-UploadId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "fid",
                        "name": "fid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/oss/upload/multipart/complete/{fid}": {
            "post": {
                "description": "完成分片上传",
                "tags": [
                    "文件上传"
                ],
                "summary": "完成分片上传",
                "parameters": [
                    {
                        "type": "string",
                        "description": "upload_id",
                        "name": "X-Oss-UploadId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "upload_key",
                        "name": "X-Oss-UploadKey",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "fid",
                        "name": "fid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/oss/upload/multipart/{fid}": {
            "post": {
                "description": "分片上传",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件上传"
                ],
                "summary": "分片上传",
                "parameters": [
                    {
                        "type": "string",
                        "description": "fid",
                        "name": "fid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "part_bytes",
                        "name": "part_bytes",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "upload_id",
                        "name": "X-Oss-UploadId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "upload_key",
                        "name": "X-Oss-UploadKey",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "content_length",
                        "name": "content_length",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "part_number",
                        "name": "part_number",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/oss/upload/putFile/{fid}": {
            "post": {
                "description": "直接上传文件",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件上传"
                ],
                "summary": "上传文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "fid",
                        "name": "fid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "file_name",
                        "name": "file_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "aws.UploadInfo": {
            "type": "object",
            "properties": {
                "content_length": {
                    "type": "integer"
                },
                "content_md5": {
                    "type": "string"
                },
                "content_type": {
                    "type": "string"
                },
                "fid": {
                    "type": "string"
                },
                "file_name": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "part_size": {
                    "type": "integer"
                }
            }
        },
        "handlers.loginInfo": {
            "type": "object",
            "properties": {
                "captcha_code": {
                    "description": "验证码",
                    "type": "string"
                },
                "captcha_id": {
                    "description": "验证码id",
                    "type": "string"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "verify_code": {
                    "description": "邮箱验证码信息",
                    "type": "string"
                }
            }
        },
        "response.Result": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "http://localhost:8888",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "共享视界",
	Description:      "共享视界后端，供app和web端调用",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
