basePath: /api/v1
definitions:
  handlers.loginInfo:
    properties:
      captcha_code:
        description: 验证码
        type: string
      captcha_id:
        description: 验证码id
        type: string
      email:
        description: 邮箱
        type: string
      password:
        description: 密码
        type: string
      verify_code:
        description: 邮箱验证码信息
        type: string
    type: object
  response.Result:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
      time:
        type: string
    type: object
host: localhost:8888
info:
  contact:
    email: duaaron519@gmail.com
    name: Aaron
  description: 共享视界后端，供app和web端调用
  title: 共享视界
  version: 0.1.0
paths:
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 登录信息
        in: body
        name: loginInfo
        required: true
        schema:
          $ref: '#/definitions/handlers.loginInfo'
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功
          schema:
            $ref: '#/definitions/response.Result'
      summary: 用户登录
      tags:
      - 登录
swagger: "2.0"
